[package]
name = "dice-duel"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]
doctest = false

[dependencies]
soroban-sdk = { workspace = true }

[dev-dependencies]
soroban-sdk = { workspace = true, features = ["testutils"] }
mock-game-hub = { path = "../mock-game-hub", features = ["testutils"] }
sha2 = "0.10.9"
stellar-xdr = "27.0.0"
